version: "3"
services:
  usertest:
    image: usertest:latest
    build:
      context: ../../../ApplicazioneRestSpring-main
      dockerfile: Dockerfile
    container_name: usertest
    restart: always
    ports:
      - 8080:8080
    networks:
      - usertest
networks:
  usertest:
    external: true